#ifndef USAGEENVIRONMENT_GLOBAL_H
#define USAGEENVIRONMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USAGEENVIRONMENT_LIBRARY)
#  define USAGEENVIRONMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USAGEENVIRONMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USAGEENVIRONMENT_GLOBAL_H
